model_name: "hyenadna-tiny-1k-seqlen-d256"
n_layer: 2
vocab_size: 12
batch_size: 2
resid_dropout: 0.0
embed_dropout: 0.1
fused_mlp: False,   
fused_dropout_add_ln: True
residual_in_fp32: True
checkpoint_mixer: False
checkpoint_mlp: False
pad_vocab_size_multiple: 8
return_hidden_state: True
device: "cpu"
layer: 
    "_name_": "hyena"
    "emb_dim": 5
    "filter_order": 64
    "local_order": 3
    "l_max": 1026
    "modulate": True
    "w": 10
    "lr": 6e-4
    "wd": 0.0
    "lr_pos_emb": 0.0
    "d_model": ???
